/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MegaWrenchDashboardSite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "MegaWrenchDefaultSite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "MegaWrenchRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}

import "sst"
export {}